### ISSUE TITLE
Test publish fails on ubuntu-latest

### ISSUE THREAD

**Issue by christianrauch** [colcon/ci#27]
Since very recently, the "Test publish" fails on "ubuntu-latest"
```
##[group]Test publish
/tmp/tmp.NsNo80JzaV ~/work/colcon-meson/colcon-meson
Cloning into '.'...
~/work/colcon-meson/colcon-meson
[...]
Creating tar archive
removing 'colcon_meson-0.4.5' (and everything under it)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/colcon_meson
copying colcon_meson/__init__.py -> build/lib/colcon_meson
copying colcon_meson/build.py -> build/lib/colcon_meson
copying colcon_meson/identification.py -> build/lib/colcon_meson
/tmp/tmp.xOjrAgXcqG/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/colcon_meson
copying build/lib/colcon_meson/__init__.py -> build/bdist.linux-x86_64/wheel/colcon_meson
copying build/lib/colcon_meson/build.py -> build/bdist.linux-x86_64/wheel/colcon_meson
copying build/lib/colcon_meson/identification.py -> build/bdist.linux-x86_64/wheel/colcon_meson
running install_egg_info
Copying colcon_meson.egg-info to build/bdist.linux-x86_64/wheel/colcon_meson-0.4.5-py3.10.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/colcon_meson-0.4.5.dist-info/WHEEL
creating 'dist/colcon_meson-0.4.5-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'colcon_meson/__init__.py'
adding 'colcon_meson/build.py'
adding 'colcon_meson/identification.py'
adding 'colcon_meson-0.4.5.dist-info/LICENSE'
adding 'colcon_meson-0.4.5.dist-info/METADATA'
adding 'colcon_meson-0.4.5.dist-info/WHEEL'
adding 'colcon_meson-0.4.5.dist-info/entry_points.txt'
adding 'colcon_meson-0.4.5.dist-info/top_level.txt'
adding 'colcon_meson-0.4.5.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Traceback (most recent call last):
== Determine available publishings
* wheel:pypi
* stdeb:packagecloud

== Determine package name and version
Package: colcon-meson
Version: 0.4.5

== Creating 'wheel' artifacts ...

-- Building sdist and bdist_wheel artifacts of package 'colcon-meson' 0.4.5 ...
$ /tmp/tmp.xOjrAgXcqG/bin/python setup.py sdist bdist_wheel
  File "/tmp/tmp.NsNo80JzaV/bin/publish-python", line 24, in <module>
    rc = main()
  File "/tmp/tmp.NsNo80JzaV/publish_python/cli.py", line 77, in main
    artifacts = artifact_handlers[artifact_type](config=artifact.config)
  File "/tmp/tmp.NsNo80JzaV/publish_python/artifact/wheel.py", line 23, in create_wheel
    assert os.path.exists(tarball), \
AssertionError: Failed to generate source tarball 'dist/colcon-meson-0.4.5.tar.gz'
##[error]Process completed with exit code 1.
```

Full CI log: https://github.com/colcon/colcon-meson/actions/runs/8667332221/job/23770147910?pr=15

Running `python setup.py sdist bdist_wheel` locally works.

**Comment by cottsay** [comment]
Here's the fix, but we'll need to find another solution to unblock things immediately.
https://github.com/dirk-thomas/publish-python/pull/4

**Comment by cottsay** [comment]
This should be resolved (for now) by pinning `setuptools`.
